CREATE TABLE `eb_staff_comment2` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` int unsigned DEFAULT '0' COMMENT '运营方id',
  `shop_id` int unsigned DEFAULT '0' COMMENT '商户id',
  `type` tinyint unsigned DEFAULT NULL COMMENT '月嫂类型',
  `staff_id` int unsigned NOT NULL COMMENT '月嫂id',
  `user_id` int unsigned NOT NULL COMMENT '用户id',
  `desc_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '描述',
  `score` int unsigned DEFAULT NULL COMMENT '评论分数',
  `is_top` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否置顶',
  `sc_a` int unsigned NOT NULL DEFAULT '0' COMMENT '专业护理分数',
  `sc_b` int unsigned NOT NULL DEFAULT '0' COMMENT '月子膳食分数',
  `sc_c` int unsigned NOT NULL DEFAULT '0' COMMENT '早教启蒙分数',
  `sc_d` int unsigned NOT NULL DEFAULT '0' COMMENT '育儿指导分数',
  `sc_e` int unsigned NOT NULL DEFAULT '0' COMMENT '爱心耐心分数',
  `sc_f` int unsigned NOT NULL DEFAULT '0' COMMENT '沟通技巧分数',
  `comment_time` datetime DEFAULT NULL COMMENT '评论时间',
  `img_url` json DEFAULT NULL COMMENT '评论图片',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否显示',
  `is_del` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2085 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='技师评论';